### PR TITLE
[Banner] Use IO#winsize to get the terminal width

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/4961.

### CODE REVIEW

**Comment by randythompson** [comment]
segiddins:  did you notice my last comment on the other issue, in which I discovered that the "tput" in /usr/bin works just fine, whereas the one installed in my /sw/bin directory (which I think contains a bunch of open-source add-ons) does not?  This may be an issue of a bad install of open source unrelated to anything you have going on here.

**Comment by segiddins** [comment]
Yeah,but this has been on my todo list for a while :)

**Comment by randythompson** [comment]
I am going to make a symbolic link from "/sw/bin/tput" to the version in "/usr/bin/tput" to see whether I can get by this issue.

**Comment by randythompson** [comment]
Thanks for your help in diagnosing this.  It looks like my GoogleMaps CocoaPod install is working now, after I replaced the /sw/bin/tput that was not working for root with a symbolic link to the other one in /usr/bin.  This will work as a temporary fix until your new code makes its way through.

**Comment by segiddins** [comment]
aaaand 1.8.7 has come to ruin my day again :(

**Comment by alloy** [comment]
@segiddins Maybe just use a dumb default fallback for 1.8.7, e.g. 80 cols?

**Comment by segiddins** [comment]
@alloy yeah, I guess. Or the `tput`  fallback?

**Comment by alloy** [comment]
Ah yeah, duh, makes way more sense :)

**Comment by segiddins** [comment]
Updated

**Comment by alloy** [comment]
LGTM :+1:

**Pull request merged**
