### PR TITLE
[ARGV] Add support for parsing --

### LINKED ISSUE #48: handle -- correctly
See http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html & http://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

### PR DESCRIPTION
**Pull request by segiddins**
closes #48

### CODE REVIEW

**Comment by neonichu** [comment]
LGTM

**Comment by orta** [comment]
ace

**Comment by alloy** [comment]
Nice :+1:

**Pull request merged**
