### PR TITLE
Fix issues with latest RubyGems when explicitly activating plugin gems

### LINKED ISSUE #98: CLAide incompatible with RubyGems-3.3.0+
This was originally logged in Cocoapods main issue list and in the rubygems list (where some great analysis took place, including a reference to the actual bisected commit that caused it)

Logging it here because the actual problem appears to be CLAide here using internals from RubyGems that were unsafe to touch, so an internal refactor of RubyGems for performance triggered a problem here, which transitively breaks cocoapods in combo with ruby-gems-3.3.x

A workaround for affected cocoapods users was posted on the cocoapods issue so users won't get stuck, but it *seems* to me (could be wrong) that the rubygems change was valid + desired from their perspective and the goal is to fix up CLAide here so it functions with new rubygems versions

That's the context. All technical details referenced out from one comment here: https://github.com/CocoaPods/CocoaPods/issues/11134#issuecomment-1006573500

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
There's no need to explicitly activate specifications at all, RubyGems `require` already takes care of gem activation.

Fixes #98.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
CI was not in place because it was using defunct travis-ci.org. So I updated this PR to migrate to Github Actions to be able to verify it's all good with tests. Changes also include:

* Drop support for rubies under 2.3, since they are not supported in Github Actions.
* Add testing under Ruby 3.1.

It seems all green: https://github.com/deivid-rodriguez/CLAide/actions/runs/1663461357.

**Comment by mikehardy** [comment]
Oh, if you added a `Fixes #98 ` to bug description it would auto-close related issue on merge. Literally the only nitpick I can think of :laughing:

**Comment by deivid-rodriguez** [comment]
Since this depends on someone from the CocoaPods organization to take some action, including merging this and releasing a new version of CLAide, yet there doesn't seem to be a lot of availability from their side at the moment, I will leave this sit there a couple of days and if there's no movement, consider addressing this from our side.

**Comment by deivid-rodriguez** [comment]
Thank you @dnkoutso!

I think as soon as this change is released, cocoapods plugin activation issues should be gone. I would make it a minor release I guess, given that support for old rubies was also dropped here.

**Comment by johnallen3d** [comment]
Sorry to be _that guy_ but is there any chance this will get released soon? #98 is breaking our usage of [Danger](https://danger.systems/ruby/) and we have limited control of the version of RubyGems we're using (CI maintained Docker image) forcing us to downgrade to a Ruby 3.0 image (which has RubyGems v3.2.32).

**Comment by deivid-rodriguez** [comment]
Do you always get the latest version, or a fixed problematic version? Just wondering whether a fix on the RubyGems side would make any difference for you at all.

**Comment by johnallen3d** [comment]
Thanks for checking @deivid-rodriguez! I'm looking over the [documentation for the images provided by CircleCI](https://github.com/circleci/circleci-images/blob/staging/docs/IMAGES.md) and it looks like they are built upon the official library images. In theory, if a RubyGems fix was released and pulled into the official Ruby image then it would flow to us. 

That said, we're not _forced_ to use the CircleCI images, it's more of a convenience and that they're hardened a bit. We can craft our own base image until this fix is released. I was mostly trying to get a feel for if it was worth spending the time just now.

**Comment by deivid-rodriguez** [comment]
If your images are based off official docker images, I'd say you're not getting any automatic RubyGems updates. The official base images have not updated RubyGems for a while now, see https://github.com/docker-library/ruby/issues/246.

**Comment by johnallen3d** [comment]
You're right @deivid-rodriguez, it looks like I would have to explicitly update the RubyGems version. At this point, I think I'll hang on a bit longer to see if the fix to this library is released. Thanks again for your help!

**Comment by dnkoutso** [comment]
I will ship this now!

**Comment by dnkoutso** [comment]
Shipped with 1.1.0

**Comment by mikehardy** [comment]
Hey @dnkoutso not sure if people say it enough, but I really appreciate cocoapods and the work you day making it run. Cheers

**Comment by dnkoutso** [comment]
@mikehardy appreciate that a lot! CocoaPods is a huge project with many pieces and without a lot of maintainers anymore...I wish I had more time for it.

**Comment by deivid-rodriguez** [comment]
@dnkoutso Thank you so much also from my side! If there are any issues related to these changes, please ping me!

**Comment by mikehardy** [comment]
Verified clean install of cocoapods 1.11.2 on ruby-3.1.0 (`\rm -fr ~/.rvm` then installing rvm, then installing ruby-3.1.0, the `gem install cocoapods`) results in a `pod install` that works out of the box clean now. I'll go note it on the related issues

**Comment by johnallen3d** [comment]
I can confirm that the new version is working for us as well. Thanks @deivid-rodriguez and @dnkoutso!

**Pull request merged**
